title: 'Arctic LCC'
author:
  name: 'Arctic LCC Staff'
  email: staff@arcticlcc.org
taxonomies:
  - category
  - tag
metadata:
  description: 'Arctic Landscape Conservation Cooperative'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
